### ISSUE TITLE
JSONDecode Errors for large inputs

### ISSUE THREAD

**Issue by sauadwaya** [assafelovic/gpt-researcher#116]
I have tested this with some inputs and what I found is that it works well for simple one-liner input prompts. But if the input is too large it starts throwing JSONDecodeError errors. Anyone got around this error? Another useful thing to have is to probably put multiple input prompts to chunk down the size, and click on Research when I have inputted the full query. 

```
  File "C:\Users\..\gpt-researcher\venv\Lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\..\gpt-researcher\venv\Lib\site-packages\starlette\routing.py", line 341, in handle
    await self.app(scope, receive, send)
  File "C:\Users\..\gpt-researcher\venv\Lib\site-packages\starlette\routing.py", line 82, in app
    await func(session)
  File "C:\Users\..\gpt-researcher\venv\Lib\site-packages\fastapi\routing.py", line 324, in app
    await dependant.call(**values)
  File "C:\Users\..\gpt-researcher\main.py", line 60, in websocket_endpoint
    await manager.start_streaming(task, report_type, agent, agent_role_prompt, websocket)
  File "C:\Users\..\gpt-researcher\agent\run.py", line 38, in start_streaming
    report, path = await run_agent(task, report_type, agent, agent_role_prompt, websocket)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\..\gpt-researcher\agent\run.py", line 50, in run_agent
    await assistant.conduct_research()
  File "C:\Users\..\gpt-researcher\agent\research_agent.py", line 141, in conduct_research
    search_queries = await self.create_search_queries()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\..\gpt-researcher\agent\research_agent.py", line 96, in create_search_queries
    return json.loads(result)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\json\decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 73)
```

**Comment by assafelovic** [comment]
It looks the issue was not with the large input but with generating the research questions. Can you please share what was your input?

**Comment by LBrockmanK** [comment]
I am also getting this issue for every research report I try, issue did not happen when I switched to resource report. Tried shorter vs longer prompts with no difference. Only abnormal thing I am aware I am doing is I change gpt4 to gpt3.5 since I don't have access to gpt4 yet.

Initial Prompt: VectorDB providers for scalable AI services.

Resource report followed by research report attempt.

`
["Top VectorDB providers for scalable AI services", "Comparison of VectorDB providers for AI services", "Pros and cons of using VectorDB for scalable AI services", "Customer reviews of VectorDB providers for AI services"]
Searching with query Top VectorDB providers for scalable AI services...
Scraping url https://milvus.io/ with question Top VectorDB providers for scalable AI services
Scraping url https://harishgarg.com/writing/best-vector-databases-for-ai-apps/ with question Top VectorDB providers for scalable AI services
Scraping url https://stackdiary.com/ai-vector-databases/ with question Top VectorDB providers for scalable AI services
Scraping url https://sourceforge.net/software/vector-databases/ with question Top VectorDB providers for scalable AI services
An error occurred while processing the url https://harishgarg.com/writing/best-vector-databases-for-ai-apps/: [Errno 26] Text file busy: '/home/cpnbetty/.cache/selenium/chromedriver/linux64/114.0.5735.90/chromedriver'
An error occurred while processing the url https://stackdiary.com/ai-vector-databases/: Message: Service /home/cpnbetty/.cache/selenium/chromedriver/linux64/114.0.5735.90/chromedriver unexpectedly exited. Status code was: 127

An error occurred while processing the url https://milvus.io/: Message: Service /home/cpnbetty/.cache/selenium/chromedriver/linux64/114.0.5735.90/chromedriver unexpectedly exited. Status code was: 127

An error occurred while processing the url https://sourceforge.net/software/vector-databases/: Message: Service /home/cpnbetty/.cache/selenium/chromedriver/linux64/114.0.5735.90/chromedriver unexpectedly exited. Status code was: 127

Searching with query Comparison of VectorDB providers for AI services...
Scraping url https://objectbox.io/vector-database/ with question Comparison of VectorDB providers for AI services
Scraping url https://press.ai/best-vector-databases/ with question Comparison of VectorDB providers for AI services
An error occurred while processing the url https://objectbox.io/vector-database/: Message: Service /home/cpnbetty/.cache/selenium/chromedriver/linux64/114.0.5735.90/chromedriver unexpectedly exited. Status code was: 127

An error occurred while processing the url https://press.ai/best-vector-databases/: Message: Service /home/cpnbetty/.cache/selenium/chromedriver/linux64/114.0.5735.90/chromedriver unexpectedly exited. Status code was: 127

Searching with query Pros and cons of using VectorDB for scalable AI services...
Scraping url https://lunabrain.com/blog/riding-the-ai-wave-with-vector-databases-how-they-work-and-why-vcs-love-them/ with question Pros and cons of using VectorDB for scalable AI services
Scraping url https://medium.com/@pankaj_pandey/vector-databases-a-comprehensive-analysis-of-pros-and-cons-e96d8e2e2239 with question Pros and cons of using VectorDB for scalable AI services
Scraping url https://www.nextplatform.com/2021/03/11/its-time-to-start-paying-attention-to-vector-databases/ with question Pros and cons of using VectorDB for scalable AI services
Scraping url https://mantiumai.com/blog/vector-databases-vs-graph-databases-a-comprehensive-comparison/ with question Pros and cons of using VectorDB for scalable AI services
An error occurred while processing the url https://www.nextplatform.com/2021/03/11/its-time-to-start-paying-attention-to-vector-databases/: Message: Service /home/cpnbetty/.cache/selenium/chromedriver/linux64/114.0.5735.90/chromedriver unexpectedly exited. Status code was: 127

An error occurred while processing the url https://lunabrain.com/blog/riding-the-ai-wave-with-vector-databases-how-they-work-and-why-vcs-love-them/: Message: Service /home/cpnbetty/.cache/selenium/chromedriver/linux64/114.0.5735.90/chromedriver unexpectedly exited. Status code was: 127

An error occurred while processing the url https://mantiumai.com/blog/vector-databases-vs-graph-databases-a-comprehensive-comparison/: Message: Service /home/cpnbetty/.cache/selenium/chromedriver/linux64/114.0.5735.90/chromedriver unexpectedly exited. Status code was: 127

An error occurred while processing the url https://medium.com/@pankaj_pandey/vector-databases-a-comprehensive-analysis-of-pros-and-cons-e96d8e2e2239: Message: Service /home/cpnbetty/.cache/selenium/chromedriver/linux64/114.0.5735.90/chromedriver unexpectedly exited. Status code was: 127

Searching with query Customer reviews of VectorDB providers for AI services...
Scraping url https://www.trustradius.com/vector-databases with question Customer reviews of VectorDB providers for AI services
Scraping url https://www.g2.com/categories/vector-database with question Customer reviews of VectorDB providers for AI services
An error occurred while processing the url https://www.g2.com/categories/vector-database: Message: Service /home/cpnbetty/.cache/selenium/chromedriver/linux64/114.0.5735.90/chromedriver unexpectedly exited. Status code was: 127

An error occurred while processing the url https://www.trustradius.com/vector-databases: Message: Service /home/cpnbetty/.cache/selenium/chromedriver/linux64/114.0.5735.90/chromedriver unexpectedly exited. Status code was: 127

streaming response...
streaming response complete
resource_report written to ./outputs/c78d3184-8925-4317-8503-fb2c5ac24c99/resource_report.pdf
INFO:     127.0.0.1:32826 - "GET /c78d3184-8925-4317-8503-fb2c5ac24c99/resource_report.pdf HTTP/1.1" 200 OK
INFO:     127.0.0.1:32826 - "GET /favicon.ico HTTP/1.1" 404 Not Found
INFO:     ('127.0.0.1', 39812) - "WebSocket /ws" [accepted]
["Top VectorDB providers for scalable AI services"]
["Comparing VectorDB providers for scalable AI services"]
["Benefits of using VectorDB for scalable AI services"]
["Customer reviews of VectorDB providers for scalable AI services"]
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/cpnbetty/.local/lib/python3.10/site-packages/uvicorn/protocols/websockets/wsproto_impl.py", line 234, in run_asgi
    result = await self.app(self.scope, self.receive, self.send)
  File "/home/cpnbetty/.local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/home/cpnbetty/.local/lib/python3.10/site-packages/fastapi/applications.py", line 289, in __call__
    await super().__call__(scope, receive, send)
  File "/home/cpnbetty/.local/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/cpnbetty/.local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 149, in __call__
    await self.app(scope, receive, send)
  File "/home/cpnbetty/.local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/cpnbetty/.local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/cpnbetty/.local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/home/cpnbetty/.local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/home/cpnbetty/.local/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/cpnbetty/.local/lib/python3.10/site-packages/starlette/routing.py", line 341, in handle
    await self.app(scope, receive, send)
  File "/home/cpnbetty/.local/lib/python3.10/site-packages/starlette/routing.py", line 82, in app
    await func(session)
  File "/home/cpnbetty/.local/lib/python3.10/site-packages/fastapi/routing.py", line 324, in app
    await dependant.call(**values)
  File "/home/cpnbetty/gpt-researcher/main.py", line 60, in websocket_endpoint
    await manager.start_streaming(task, report_type, agent, agent_role_prompt, websocket)
  File "/home/cpnbetty/gpt-researcher/agent/run.py", line 38, in start_streaming
    report, path = await run_agent(task, report_type, agent, agent_role_prompt, websocket)
  File "/home/cpnbetty/gpt-researcher/agent/run.py", line 50, in run_agent
    await assistant.conduct_research()
  File "/home/cpnbetty/gpt-researcher/agent/research_agent.py", line 141, in conduct_research
    search_queries = await self.create_search_queries()
  File "/home/cpnbetty/gpt-researcher/agent/research_agent.py", line 96, in create_search_queries
    return json.loads(result)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 52)
`

**Comment by rotemweiss57** [comment]
please follow this thread: https://github.com/assafelovic/gpt-researcher/issues/14 it contains a temporary solution for using gpt-3.5.
