### ISSUE TITLE
Config file does not update with docker

### ISSUE THREAD

**Issue by jore92** [assafelovic/gpt-researcher#164]
Hello! I'm using docker on macOS to spin up the app. I changed the model on line 26 of config.py to `self.smart_llm_model = os.getenv("SMART_LLM_MODEL", "gpt3.5-turbo")`. I restarted the docker container, still showed: `openai.error.InvalidRequestError: The model `gpt-4` does not exist or you do not have access to it.`. I then deleted the container  and ran docker-compose again, same issue. Note: I have premium chatGPT so I should have access to GPT4 nonetheless. I've attached the console log of the full stack trace of the error. I also manually tried to add my openai key to docker file and still same issue
[gpt-researcher-log.txt](https://github.com/assafelovic/gpt-researcher/files/12525424/gpt-researcher-log.txt)

**Comment by assafelovic** [comment]
That is very strange since no where in the code are we pulling a static "gpt-4" model. Every instance where a model is called it uses the "SMART_LLM_MODEL" param. Since "SMART_LLM_MODEL" first checks for existing env variable may it be that it's saved locally? Try statically setting the var to "gpt3.5-turbo" and try again. Let me know!

**Comment by assafelovic** [comment]
Closing this for now due to inactivity. Please let us know if the issue persists.
