### ISSUE TITLE
Not enough tokens error, although I've paid A LOT

### ISSUE THREAD

**Issue by resonates7** [assafelovic/gpt-researcher#176]
This is related to [issue #153 ](https://github.com/assafelovic/gpt-researcher/issues/153), which was closed but not resolved. I didn't see a way to reopen that issue.

I'm posting this here out of exasperation with OpenAI's customer service after exchanging dozens of messages with them. My interaction with OpenAI customer support has been beyond terrible. I understand it's a startup, but I hope they'll devote some time and attention to making customer service work for their customers.

Basically, I'm getting an error message shown in screenshot 2 that I'm lacking about 3k tokens to complete the request. However, the OpenAPI website (screenshot 3) says I have $50+ balance, which is more than enough tokens. I can't seem to convince OpenAI that I've paid for the tokens even though they've been charging my credit card for almost a month (screenshot1). They seem convinced I still have a free account.

I'm hoping someone here can help me fix this or at least suggest a strategy for dealing with Open AI that won't result in weeks of wasted effort and frustration.

![screenshot1](https://github.com/assafelovic/gpt-researcher/assets/49754697/21488dd7-9a9c-4432-8180-c58b9342ea9c)
![screenshot2](https://github.com/assafelovic/gpt-researcher/assets/49754697/bf6b4112-a49b-4389-83ef-056bfe6de289)
![Screenshot3](https://github.com/assafelovic/gpt-researcher/assets/49754697/76b41d16-0d82-4a5e-bdc6-daa3ec585b88)

**Comment by assafelovic** [comment]
Hey @resonates7 I can definitely understand your frustration. The irony with OpenAI is their disruption of AI vs the inability to leverage it for customer support :)

The error you're seeing is not related to your balance, but rather to the fact that each GPT model has token size limitations, meaning the amount of words it can handle/generate. For GPT 3.5 it's 4K which is what you're seeing in the error. This may due to edge cases in our service where GPT Researcher summarizes texts that are too long, however this should not happen in most cases, also since we've updated the model to use gpt3.5-16k which has a 16k token window. Have you modified the code to use only GPT3.5?

**Comment by resonates7** [comment]
Yes, and I've been able to fix it by changing it to gpt3.5-16k in the config file. Thanks for the tip!
