### ISSUE TITLE
Pls support Pinecone Retriever

### ISSUE THREAD

**Issue by SeanJAmmirati** [assafelovic/gpt-researcher#379]
We have checked your research assistant and it does a great job searching the web.  However, we also would also like to have agents search across our Pinecone vector store.  

From your blog post: https://blog.langchain.dev/exploring-uxs-besides-chat-with-research-assistant/
"It can equally easily be pointed to a vectorstore containing your relevant information."

But not sure when this will be done from your roadmap or if I'm just missing how to configure this.  Any advice would be welcome.

**Comment by djuillard** [comment]
Hi, I have worked as well on this repo and the architecture, the sequencing are really smart.... and results are indeed very great -> impressive work. 
I also support @SeanJAmmirati request because in a market study for instance, it can make sense to add proprietary document into the global search in parallel to internet sources. Thanks

**Comment by SomethingGoodLLC** [comment]
How would PineCone help?

On Apr 4, 2024, at 05:17, djuillard ***@***.***> wrote:

﻿

Hi, I have worked as well on this repo and the architecture, the sequencing are really smart.... and results are indeed very great -> impressive work.
I also support @SeanJAmmirati<https://github.com/SeanJAmmirati> request because in a market study for instance, it can make sense to add proprietary document into the global search in parallel to internet sources. Thanks

**Comment by SeanJAmmirati** [comment]
Does my explanation make sense?  Any update on this?

**Comment by assafelovic** [comment]
Hey, although this is not my personal roadmap, happy to see if anyone from the community would be interested in this integration. Should be quite simple by adding another provider here: https://github.com/assafelovic/gpt-researcher/blob/master/gpt_researcher/memory/embeddings.py
