### ISSUE TITLE
update pypi package

### ISSUE THREAD

**Issue by Undertone0809** [assafelovic/gpt-researcher#394]
It is great if you can update the pypi package at the same time when you release the latest version.

![image](https://github.com/assafelovic/gpt-researcher/assets/72488598/c63cf1ef-7683-4458-898d-99fec54fc5d6)

**Comment by nileshtrivedi** [comment]
Even when specifying the requirement directly from github, I get many dependency conflicts, like:

> The conflict is caused by:
> 94.52     The user requested pydantic==2.6.4
> 94.52     fastapi 0.110.0 depends on pydantic!=1.8, !=1.8.1, !=2.0.0, !=2.0.1, !=2.1.0, <3.0.0 and >=1.7.4
> 94.52     langchain 0.1.12 depends on pydantic<3 and >=1
> 94.52     langchain-core 0.1.32 depends on pydantic<3 and >=1
> 94.52     langsmith 0.1.27 depends on pydantic<3 and >=1
> 94.52     openai-function-call 0.2.6 depends on pydantic<3.0.0 and >=2.0.2
> 94.52     gpt-researcher 0.0.5 depends on pydantic==2.5.1

This is because the dependencies mentioned in pyproject.toml are very strict and conflict with the project which is trying to use this package.

Also, the version mentioned in pyproject.toml (0.0.5) does not match the git tag (0.1.5).

**Comment by assafelovic** [comment]
Done! https://pypi.org/project/gpt-researcher/

**Comment by nileshtrivedi** [comment]
Thanks @assafelovic 

It would help if in pyproject.toml, the dependencies' versions are specified with ">=" rather than exact version. This helps when gpt-researcher is used as a library in another python project and minimizes version conflicts. 

For example, instead of:
```
asyncio = "3.4.3"
```
it should say,
```
asyncio = ">=3.4.3"
```

This lets the library user upgrade their dependencies even if gpt-researcher version is a bit behind the times. 
Other version specification operators like caret, tilda are also available and might be more appropriate.
They are documented [here in Poetry docs](https://python-poetry.org/docs/dependency-specification/).
