### ISSUE TITLE
Secure the API

### ISSUE THREAD

**Issue by mcantrell** [assafelovic/gpt-researcher#916]
Given that the API provides endpoints (`getConfig`) to view secret keys, security seems necessary. 

The current documentation probably also needs to be updated to reflect that the server should not be openly exposed to the internet due to the security risk (until this feature is added).

**Comment by assafelovic** [comment]
Which API are you referring to? Sorry not exactly understanding the main issue here

**Comment by mcantrell** [comment]
The docker container binds a python fastapi to all network adapters and exposes the API security keys to everyone who has network access:

<img width="1482" alt="image" src="https://github.com/user-attachments/assets/b4fed148-a9f2-4b1c-b9d4-9cdc14fa2416">

To limit the potential for security leaks, maybe the services should only be available over localhost until there is a method to secure the API.

**Comment by ElishaKay** [comment]
great call @mcantrell 

The original idea for the `getConfig` & `setConfig` routes was to make the onboarding experience smoother for running in development mode - i.e. so that developers getting started with the repo will have a clearer understanding of which variables are required for which features of the app.

I wonder what it would take to make this "dev"=>"production" flow smoother.

Maybe an env variable `MODE` which equals `development` or `production` & defaults to `development`

Based on the value of this variable we could conditionally hide or expose this route

True, we'll need to clarify the docs, as well in the meantime to warn users.

Would you like to give it a go with the PR so we can carve your name into the git tree?

**Comment by mcantrell** [comment]
I think that changing the settings to use localhost by default would be enough really. That would certainly go a long way.

Maybe the security part should be up to the developer. I think we're planning on making a fork of the API and making our own UI with Auth0 integration for security but that might not be everyone's cup of tea.

**Comment by ElishaKay** [comment]
We removed the `getConfig` and `setConfig` routes for now.
Perhaps we'll revisit it in a later sprint.
